config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users, except: [:new], path: 'usuarios'

  get '/cadastro', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence:true, length{minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :impede_logado, only: [:new]
    before_action :impede_nao_logado, only: [:destroy]

    def new 
    end

    def create
        user= User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            log_in(user)
            redirect_to user
        else
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_path
    end

    private

    def impede_nao_logado
        if !logged_in?
            redirect_to login_path
        end
    end

    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def Pages
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :impede_logado, only: [:home]


    def home
    end

    private

    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end
end

app/controllers/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence:true, length: {minimum: 6}
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :impede_nao_logado, except: [:new, :create]
    before_action :impede_logado, only: [:new]  

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to @user
        else 
            render 'new'
        end
    end

    def index
    end

    def show
        @user=User.find(params[:id])
    end
    
    private

    def user_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end

    def impede_nao_logado
        if !logged_in?
            redirect_to root_path
        end
    end

    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            if @current_user.nil?
                @current_user = User.find_by(id: session[:user_id])
            else
                @current_user
            end
        end    
    end
    
    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user=nil
    end
    
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to 'Sair', logout_path, method: :delete%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/Pages.html.erb
<h1>Static#Pages</h1>
<p>Find me in app/views/static/Pages.html.erb</p>

app/views/static_pages/home.html.erb
<h1>BEM VINDO AO NOSSO SITE!</h1>

<%= link_to 'Cadastre-se agora!', cadastro_path %>
<%= link_to 'Faça login aqui!', login_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

    <div class= 'field'>
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name %>
    </div>

    <div class= 'field'>
        <%= form.label :email, 'E-mail' %>
        <%= form.email_field :email %>
    </div>

    <div class= 'field'>
        <%= form.label :password, 'Senha' %>
        <%= form.password_field :password %>
    </div>

    <div class= 'field'>
        <%=form.label :password_confirmation, "Confirmar senha" %>
        <%=form.password_field :password_confirmation %>
    </div>

    <div class= 'actions'>
        <%= form.submit 'Cadastrar' %>
    </div>   
    

<% end %>

app/views/users/index.html.erb
<h1>VOCÊ ESTÁ LOGADO!</h1>

app/views/users/new.html.erb
<h1>CADASTRE-SE!</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<%= @user.name %> <%= @user.email%>